data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.pascal_dataset
        class: PascalDataset
        PascalDataset:
          image_size: 300
          VOC2012:
            image_dir: '''../efficient_det_pytorch/dataset/PASCALVOC2012/JPEGImages/'''
            label_dir: '''../efficient_det_pytorch/dataset/PASCALVOC2012/Annotations/'''
            txt_path: '''../efficient_det_pytorch/dataset/PASCALVOC2012/ImageSets/Segmentation/val.txt'''
          VOC2007:
            image_dir: '''../efficient_det_pytorch/dataset/PASCALVOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007/JPEGImages/'''
            label_dir: '''../efficient_det_pytorch/dataset/PASCALVOC2007/VOCtest_06-Nov-2007/VOCdevkit/VOC2007/Annotations/'''
          image_extent: '''.jpg'''
          label_extent: '''.xml'''
          # mean: [0.485, 0.456, 0.406]
          # std: [0.229, 0.224, 0.225]
          classes:
            aeroplane: 1
            bicycle: 2
            bird: 3
            boat: 4
            bottle: 5
            bus: 6
            car: 7
            cat: 8
            chair: 9
            cow: 10
            diningtable: 11
            dog: 12
            horse: 13
            motorbike: 14
            person: 15
            pottedplant: 16
            sheep: 17
            sofa: 18
            train: 19
            tvmonitor: 20
      batch_size: 32
      shuffle: False
      pin_memory: True
      num_workers: 12
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.ssd300_vgg16
  class: SSD300VGG16
  SSD300VGG16:
    num_classes: 21
    pretrained: False
    pretrained_backbone: False

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.evaluator
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mAP
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                aeroplane: 1
                bicycle: 2
                bird: 3
                boat: 4
                bottle: 5
                bus: 6
                car: 7
                cat: 8
                chair: 9
                cow: 10
                diningtable: 11
                dog: 12
                horse: 13
                motorbike: 14
                person: 15
                pottedplant: 16
                sheep: 17
                sofa: 18
                train: 19
                tvmonitor: 20
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/PASCAL/ssd300/2110111509/best_model_13_mAP=0.7341.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/PASCAL/ssd300/2110111509/best_model_13_mAP=0.7341/'''
    image_size: 300
    classes:
      aeroplane: [[128, 0, 0], 1]  # color, class_idx, area_threshold
      bicycle: [[0, 128, 0], 2]
      bird: [[128, 128, 0], 3]
      boat: [[0, 0, 128], 4]
      bottle: [[128, 0, 128], 5]
      bus: [[0, 128, 128], 6]
      car: [[128, 128, 128], 7]
      cat: [[64, 0, 0], 8]
      chair: [[192, 0, 0], 9]
      cow: [[64, 128, 0], 10]
      diningtable: [[192, 128, 0], 11]
      dog: [[64, 0, 128], 12]
      horse: [[192, 0, 128], 13]
      motorbike: [[64, 128, 128], 14]
      person: [[192, 128, 128], 15]
      pottedplant: [[0, 64, 0], 16]
      sheep: [[128, 64, 0], 17]
      sofa: [[0, 192, 0], 18]
      train: [[128, 192, 0], 19]
      tvmonitor: [[0, 64, 128], 20]
    iou_threshold: 0.5
    score_threshold: 0.2
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
