data:
  test:
      module: torch.utils.data
      class: DataLoader
      DataLoader:
        dataset:
          module: flame.core.data.voc_dataset
          class: VOCDataset
          VOCDataset:
            input_dir: '''../efficient_det_pytorch/dataset/VOC2007/test'''
            image_size: 300
            classes:
              aeroplane: 0
              bicycle: 1
              bird: 2
              boat: 3
              bottle: 4
              bus: 5
              car: 6
              cat: 7
              chair: 8
              cow: 9
              diningtable: 10
              dog: 11
              horse: 12
              motorbike: 13
              person: 14
              pottedplant: 15
              sheep: 16
              sofa: 17
              train: 18
              tvmonitor: 19
            image_pattern: '''*.jpg'''
            label_pattern: '''*.xml'''
        batch_size: 16
        shuffle: False
        collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.ssd300_vgg16
  class: SSD300VGG16
  SSD300VGG16:
    num_classes: 20
    pretrained: False
    pretrained_backbone: False

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mAP
        class: mAP
        mAP:
          num_classes: 20
          iou_threshold: 0.5
          box_format: '''corners'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: ''''''
    mode: '''test'''

predictor:
  module: flame.handlers.voc2007_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: ''''''
    image_size: (300, 300)
    use_pad_to_square: True
    classes:
      aeroplane: [[128, 0, 0], 0]  # color, class_idx
      bicycle: [[0, 128, 0], 1]
      bird: [[128, 128, 0], 2]
      boat: [[0, 0, 128], 3]
      bottle: [[128, 0, 128], 4]
      bus: [[0, 128, 128], 5]
      car: [[128, 128, 128], 6]
      cat: [[64, 0, 0], 7]
      chair: [[192, 0, 0], 8]
      cow: [[64, 128, 0], 9]
      diningtable: [[192, 128, 0], 10]
      dog: [[64, 0, 128], 11]
      horse: [[192, 0, 128], 12]
      motorbike: [[64, 128, 128], 13]
      person: [[192, 128, 128], 14]
      pottedplant: [[0, 64, 0], 15]
      sheep: [[128, 64, 0], 16]
      sofa: [[0, 192, 0], 17]
      train: [[128, 192, 0], 18]
      tvmonitor: [[0, 64, 128], 19]
    thresh_score: 0.4
    thresh_iou_nms: 0.5
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.engine
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
